##!/usr/bin/env bash
CACHE_TARGET_DIRECTORY="$SYSTEM_DIR/cache"
CACHE_ORIGINAL_DIRECTORY="$HOME/.cache"
echo Mount Cache directory
mv "$CACHE_ORIGINAL_DIRECTORY" "$CACHE_TARGET_DIRECTORY"
rm -rf "$CACHE_ORIGINAL_DIRECTORY" || true
sudo mount --rbind "$CACHE_TARGET_DIRECTORY" "$CACHE_ORIGINAL_DIRECTORY"
