stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: ""


test_with_docker:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - mkdir data
  script:
    - make tests_in_docker
