stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: "" # For use of a local runner

test_with_docker:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - mkdir data
  script:
    - make tests_in_docker

test_real_installs:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - adduser clement --disabled-password --no-create-home
    - mkdir data
    - chown -r clement .
  script:
    - make debug_ci

test_real_install_biglybt:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - mkdir data
  script:
    - make test_real_install_biglybt