stages:
  - test

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: "" # For use of a local runner

tests:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - mkdir data
  script:
    - make tests

test_real_installs:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - adduser clement --disabled-password --no-create-home
    - mkdir data
    - chown -R clement .
  script:
    - make test_real_installs

test_real_install_biglybt:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - adduser clement --disabled-password --no-create-home
    - mkdir data
    - chown -R clement .
  script:
    - make test_real_install_biglybt

test_helpers:
  stage: test
  image: "docker:latest"
  services:
    - docker:dind
  before_script:
    - apk add make bash
    - mkdir data
  script:
    - make test_helpers

test_non_bats:
  stage: test
  image: bash
  before_script:
    - apk add make
    - mkdir data
  script:
    -