##!/usr/bin/env bash
ENCRYPTED_DIR="$HOME/encrypted"
echo Encrypted directory : $ENCRYPTED_DIR
APP_DIR="$ENCRYPTED_DIR/app"
MINICONDA_DIR="$APP_DIR/miniconda"
INSTALLATION_DIR="$ENCRYPTED_DIR/installation"
NEW_UBUNTU_INSTALLATION_DIR="$INSTALLATION_DIR/new_ubuntu"
BASHRC_FILE="$HOME/.bashrc"
FILES_DIR="$NEW_UBUNTU_INSTALLATION_DIR/files"
SYSTEM_DIR="$ENCRYPTED_DIR/system"
